<?php
    $logoUrl =  $block->getLogoSrc();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

?>
<?php if($block->isHomePage()) : ?>
    <meta property="og:url" content="<?php echo $storeManager->getStore()->getBaseUrl(); ?>">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Hacano- Homepage">
    <meta property="og:description" content="Default Description">
    <meta property="og:image" content="<?php echo $logoUrl; ?>" />
<?php endif; ?>