<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */

$mageTopHelper = $this->helper('\Magetop\Quickview\Helper\Data');
$productUrl = $mageTopHelper->getUrl();
$baseUrl = $mageTopHelper->getBaseUrl();
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <span class="decrement"><?= __('-') ?></span>
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <span class="increment"><?= __('+') ?></span>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
            <div class="action-addtional actions">
                <button id="buy-now" type="button"
                        title="<?= $block->escapeHtmlAttr(__('Add To Cart')) ?>"
                        class="primary">
                    <span class="label1"><?= $block->escapeHtml(__('Buy Now')) ?></span>
                    <span class="label2"><?= $block->escapeHtml(__('Buy Now')) ?></span>
                </button>
            </div>
        </div>
    </div>
    <div class="fixed-box">
        <span id="fixed-box-buy-later"><?= __('Add to Cart') ?></span>
        <span id="fixed-box-buy-now" data-quickview-url=""><?= __('Buy Now') ?></span>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

<script>
   require(['jquery', 'Magetop_Quickview/js/quick_view_product'], function($, popupWidget) {
        function openPopup(prodUrl){
            $.magnificPopup.open(
                {
                    items: {
                        src: prodUrl
                    },
                    type: 'iframe',
                    closeOnBgClick: true,
                    showCloseBtn: true,
                    scrolling: false,
                    preloader: true,
                    tLoading: '',
                    callbacks: {
                        open: function () {
                            $('.mfp-preloader').css('display', 'block');
                            $("iframe.mfp-iframe").contents().find("html").addClass("magetop_loader");
                        },
                        beforeClose: function () {
                            $('[data-block="minicart"]').trigger('contentLoading');
                            $.ajax(
                                {
                                    url: "<?= $baseUrl ?>",
                                    method: "POST"
                                }
                            );
                        },
                        close: function () {
                            $('.mfp-preloader').css('display', 'none');
                        }
                    }
                }
            );
        }

        $('#fixed-box-buy-later').on('click', function () {
            var id_product  =   $("input[name='product']").val();
            var prodUrl = "<?= $productUrl ?>" + 'id/' + id_product + '?type=buylater';
            if (prodUrl.length) {
               openPopup(prodUrl);
            }
        });

        $('#fixed-box-buy-now').on('click', function () {
            var id_product  =   $("input[name='product']").val();
            var prodUrl = "<?= $productUrl ?>" + 'id/' + id_product + '?type=buynow';
            if (prodUrl.length) {
               openPopup(prodUrl);
            }
        });

        $(document).ready(function() {
            $("#buy-now").on("click", function() {
                // Add input text hidden for check is buy now
                let htmlInputIsBuyNow   =   "<input type='hidden' name='is-buy-now' id='is-buy-now' value='1' />";
                if($("#is-buy-now").length <= 0) {
                    $("#product_addtocart_form").prepend(htmlInputIsBuyNow);
                }
                $("#product-addtocart-button").click();

                // Remove if have error not choose option

                $("#is-buy-now").remove();
            })

            if($(window).width() <= 767) {
                $(window).scroll(function (event) {
                    $(".catalog-product-view").not(".btn-buy-now-body").not(".btn-buy-later-body").find(".box-tocart").hide();
                    $(".fixed-box").addClass("enable-fixed");
                });
            }

            $(".box-tocart .field.qty .control > span.increment").on("click", function() {
                var inputVal    =   $("#qty").val();
                var inputValIncrement   =   parseInt(inputVal) + 1;
                $("#qty").val(inputValIncrement);
            })

            $(".box-tocart .field.qty .control > span.decrement").on("click", function() {
                var inputVal    =   $("#qty").val();
                var inputValIncrement   =   parseInt(inputVal) - 1;
                $("#qty").val(inputValIncrement);
            })

        })
    })
</script>

<style>


    #buy-now span {
        display: none;
    }

    body:not(.btn-buy-now) #buy-now span.label2 {
        display: block;
        background-color: #343434;
        color: #fff;
    }

    .btn-buy-now-body #buy-now span.label1 {
        display: block;
        background-color: #787878;
        color: #fff;
    }

    #fixed-box {
        display: none;
    }

    .magetop_quickview-catalog_product-view .fixed-box {
        display: none !important;
    }

    .btn-buy-now-body #product-addtocart-button {
        display: none;
    }

    .btn-buy-now-body #product-addtocart-button {
        display: none;
    }

    .btn-buy-now-body #buy-now {
        width: 100%;
        height: 3rem;
        padding: 0 2em;
        margin-bottom: 0;
        overflow: hidden;
        text-transform: uppercase;
        font-size: 1em;
        letter-spacing: -.015em;
        font-weight: 700;
        line-height: 3rem;
        border: none;
        background: #343434 !important;
        border-color: #343434 !important;
        color: #fff !important;
    }

    .box-tocart #buy-now {
        height: 3rem;
        min-width: 150px;
        padding: 0 2em;
        overflow: hidden;
        text-transform: uppercase;
        font-size: 16px;
        letter-spacing: -.015em;
        font-weight: 700;
        line-height: 3rem;
        border: none;
        margin-left: 0;
        background: #343434;
        color: #fff !important;
        width: 100%;
    }

    .btn-buy-later-body #buy-now {
        display: none;
    }

    @media(min-width: 768px) {
        .box-tocart  > .fieldset {
            display: flex;
        }

        .quickview-block-top,
        .product-info-main {
            width: 50% !important;
            max-width: 50% !important;
            padding: 20px;
        }

        .btn-buy-now-body .column.main {
            display: flex;
        }

        .btn-buy-now-body .column.main .quickview-block-top .product.media {
            width: 100%;
        }
    }
    @media(max-width: 767px) {
        .fixed-box.enable-fixed {
            position: fixed;
            z-index: 1000;
            background: #fff;
            left: 0;
            bottom: 0;
            right: 0;
        }

        .fixed-box.enable-fixed {
            display: flex;
            justify-content: space-between;
        }

        .fixed-box.enable-fixed > span {
            width: calc(50%);
            max-width: 50%;
            box-sizing: border-box;
            display: inline-block;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        #fixed-box-buy-now {
            background-color: #343434;
            color: #fff;
        }

        #fixed-box-buy-later {
            background-color: #787878;
            color: #fff;
        }

        /* .btn-buy-now-body .product-info-stock-sku,
        .btn-buy-later-body .product-info-stock-sku,
        .btn-buy-now-body .porto-block-html-top,
        .btn-buy-later-body .porto-block-html-top,
        .btn-buy-now-body .page-header ,
        .btn-buy-later-body .page-header,
        .btn-buy-now-body .product-social-links ,
        .btn-buy-later-body .product-social-links,
        .btn-buy-now-body .page-main.page-main-details,
        .btn-buy-later-body .page-main.page-main-details,
        .btn-buy-now-body .block-viewed-products-grid, 
        .btn-buy-later-body .block-viewed-products-grid,
        .btn-buy-now-body  #myBtn,
        .btn-buy-later-body  #myBtn  {
            display: none !important;
        } */

        .btn-buy-later-body #paypal-smart-button,
        .btn-buy-now-body #paypal-smart-button {
            display: none;
        }


        .mfp-iframe-holder .mfp-close {
            display: none;
        }

        .mfp-iframe-holder .mfp-content {
            position: fixed;
            left: 0;
            bottom: 0;
            right: 0;
        }

        .btn-buy-later-body .column.main,
        .btn-buy-now-body .column.main {
            padding: 0 !important;
        }

        .btn-buy-now-body .product-info-main,
        .btn-buy-later-body .product-info-main {
            margin-bottom: 0 !important;
        }

        .btn-buy-now-body .product-options-bottom ,
        .btn-buy-later-body .product-options-bottom{
            margin: 0 !important;
        }

        .btn-buy-later-body .fotorama__nav-wrap,
        .btn-buy-now-body .fotorama__nav-wrap,
        .btn-buy-now-body .fotorama__fullscreen-icon,
        .btn-buy-later-body .fotorama__fullscreen-icon{
            display: none !important;
        }   

        .quickview-block-top {
            display: flex;
            align-items: flex-end;
            padding: 20px 0;
        }

        .quickview-block-top .product.media,
        .quickview-block-top .quickview-block-top-price {
            width: 50%;
            max-width: 50%;
            box-sizing: border-box;
        }

        .quickview-block-top .product.media .fotorama__stage {
            border-radius: 15px;
        }

        .quickview-block-top .quickview-block-top-price  .normal-price .price {
            color: red;
        }

        .btn-buy-later-body .box-tocart > .fieldset,
        .btn-buy-now-body .box-tocart > .fieldset  {
            display: flex;
            flex-direction: column;
        }

        .btn-buy-later-body .box-tocart > .fieldset .field.qty .label,
        .btn-buy-now-body .box-tocart > .fieldset  .field.qty .label {
            display: block;
        }

        .btn-buy-later-body .box-tocart > .fieldset .field.qty,
        .btn-buy-now-body .box-tocart > .fieldset  .field.qty  {
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .btn-buy-later-body  .product-add-form .box-tocart,
        .btn-buy-now-body  .product-add-form .box-tocart{
            border: none !important;
        }

        .quickview-block-top-price {
            padding-left: 15px;
        }

        .mfp-iframe-holder .mfp-close {
            display: block !important;
            right: 10px;
            top: 5px;
            transform: none;
            color: #000;
            background: transparent !important;
            user-select: all;
            font-size: 40px;
        }

        .mfp-iframe-holder .mfp-close::before,
        .mfp-iframe-holder .mfp-close::after {
            display: none;
        }
    }

    @media (hover: none) {
        .mfp-iframe-holder .mfp-close:hover { color: inherit; }
    }
    
    .box-tocart .field.qty .control {
        display: flex;
        align-items: center;
    }

    .box-tocart .field.qty .control > span {
        height: 100%;
        border: 1px solid #e7e7e7;
        display: block;
        min-height: 48px;
        line-height: 46px;
        width: 40px;
        text-align: center;
        cursor: pointer;
        box-sizing: border-box;
    }

    .box-tocart .field.qty .control #qty {
        min-height: 48px;
    }

    #paypal-smart-button {
        display: none !important;
    }
    

</style>
