<?php
use Magento\Framework\App\Action\Action;
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$_category_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category');
$_category_grid_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category_grid');
?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $hover_image = 'category_page_grid-hover';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;

    $image_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:300;
    $image_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:300;
?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-grid products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?php echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php
                                    if($_category_config['aspect_ratio'])
                                        $productImage = $_imagehelper->init($_item, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                    else
                                        $productImage = $_imagehelper->init($_item, $image)->resize($image_width, $image_height);
                                    $productImageUrl = $productImage->getUrl();
                                ?>
                                    <img class="product-image-photo default_image abc" width="240" height="300" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                                <?php if($_category_config['alternative_image']): ?>
                                <?php
                                    if($_category_config['aspect_ratio'])
                                        $productHoverImage = $_imagehelper->init($_item, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                    else
                                        $productHoverImage = $_imagehelper->init($_item, $hover_image)->resize($image_width, $image_height);
                                    $productHoverImageUrl = $productHoverImage->getUrl();
                                ?>
                                    <?php if($productImageUrl != str_replace("/thumbnail/","/small_image/",$productHoverImageUrl)): ?>
                                    <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <!-- Get brands -->
                                <div class="brands">
                                    <?php 
                                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
                                    $brandBlock = $block->getLayout()->createBlock('Magiccart\Shopbrand\Block\Product\View');
                                    $brand = $brandBlock->getBrandOfProduct($product);
                                    if(!$brand) return;
                                    
                                    // echo $product->getAttributeText('brands');
                                    ?>
                                    <?php if($brand->getData('image')) : ?>
                                        <img class="brand img-responsive" src="<?php /* @escapeNotVerified */ echo $brandBlock->getImage($brand)?>" alt="<?php /* @escapeNotVerified */ echo __($brand->getTitle()) ?>" title="<?php /* @escapeNotVerified */ echo __($brand->getTitle()) ?>" />
                                    <?php endif ?>
                                </div>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $_helper->productAttribute($_item, $_item->getName(), 'name'); ?>
                                    </a>
                                </strong>

                                <?php if($_category_config['rating_star']): ?>
                                <?php
                                    $review_html = $block->getReviewsSummaryHtml($_item, $templateType);
                                ?>
                                <?php if($review_html): ?>
                                    <?php echo $review_html; ?>
                                <?php else: ?>
                                        <?= '';?>
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                        <span class="label"><span>Rating:</span></span>
                                        <div class="rating-result" title="0%">
                                            <span style="width:0"><span>0%</span></span>
                                        </div>
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php endif; ?>

                                <?php if($_category_config['product_price']): ?>
                                <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                <?php endif; ?>

                                <?php if($_category_config['actions']): ?>
                                    <?= $block->getProductDetailsHtml($_item) ?>
                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if($_category_config['addtowishlist']): ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                   class="action towishlist actions-secondary" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <?php if($_item->getTypeId() == 'simple'): ?>
                                                            <button type="submit"
                                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary" style="display: none;">
                                                                <span><?php echo __('Add to Cart') ?></span>
                                                            </button>
                                                            <?php else: ?>
                                                            <button type="button"
                                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary popup-add-to-cart">
                                                                <span><?php echo __('Add to Cart') ?></span>
                                                            </button>
                                                            <?php endif; ?>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if($_category_config['addtocompare']): ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare actions-secondary"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>

<?php 
    $helper = $this->helper(Magetop\Quickview\Helper\Product::class);
    $btnTextColor = $helper->getBtnTextColor();
    $baseUrl = $helper->getBaseUrl();
    $buttonText = $helper->getButtonText();
    $btnBackground = $helper->getBtnBackground();
    list($r, $g, $b) = sscanf($btnBackground, "%02x%02x%02x");
    $productUrl = $helper->getUrl();
    $buttonText = $helper->getButtonText();
    $isEnabled = $helper->enabled();
    $productItemInfo = $helper->getProductItemInfo();
    $productImageWrapper = $helper->getProductImageWrapper();
?>

<script>
    require([
        'jquery',
        'mage/mage',
        'Magetop_Quickview/js/jquery.magnific-popup.min'
    ], function($) {
        $(document).ready(function() {
            $(".popup-add-to-cart").on("click", function() {
                var id_product  =   $(this).parent().find("input[name='product']").val();
                var prodUrl = "<?= $productUrl ?>"+ 'id/' + id_product + '?type=buylater';
                if (prodUrl.length) {
                    var url = "<?= $baseUrl ?>" + 'magetop_quickview/index/updatecart';
                    $.magnificPopup.open(
                        {
                            items: {
                                src: prodUrl
                            },
                            type: 'iframe',
                            closeOnBgClick: true,
                            scrolling: false,
                            preloader: true,
                            tLoading: '',
                            callbacks: {
                                open: function () {
                                    $('.mfp-preloader').css('display', 'block');
                                    $("iframe.mfp-iframe").contents().find("html").addClass("magetop_loader");
                                },
                                beforeClose: function () {
                                    $('[data-block="minicart"]').trigger('contentLoading');
                                    $.ajax(
                                        {
                                            url: url,
                                            method: "POST"
                                        }
                                    );
                                },
                                close: function () {
                                    $('.mfp-preloader').css('display', 'none');
                                }
                            }
                        }
                    );
                }
            })
        })
    })
</script>

<style>

    #fixed-box {
        display: none;
    }

    .magetop_quickview-catalog_product-view .fixed-box {
        display: none !important;
    }

    .btn-buy-now-body #product-addtocart-button {
        display: none;
    }

    .btn-buy-now-body #product-addtocart-button {
        display: none;
    }

    .btn-buy-now-body #buy-now {
        width: 100%;
        height: 3rem;
        padding: 0 2em;
        margin-bottom: 0;
        overflow: hidden;
        text-transform: uppercase;
        font-size: 1em;
        letter-spacing: -.015em;
        font-weight: 700;
        line-height: 3rem;
        border: none;
        background: #f76b6a !important;
        border-color: #f76b6a !important;
        color: #fff !important;
    }

    .box-tocart #buy-now {
        height: 3rem;
        min-width: 150px;
        padding: 0 2em;
        overflow: hidden;
        text-transform: uppercase;
        font-size: 1em;
        letter-spacing: -.015em;
        font-weight: 700;
        line-height: 3rem;
        border: none;
        margin-left: 0;
        background: #555;
        color: #fff !important;
        width: 100%;
    }

    .btn-buy-later-body #buy-now {
        display: none;
    }
    @media(max-width: 767px){
        .mfp-iframe-holder .mfp-close {
            display: block !important;
            right: 10px;
            top: 5px;
            transform: none;
            color: #000;
            background: transparent !important;
            user-select: all;
            font-size: 40px;
        }

        .mfp-iframe-holder .mfp-close::before,
        .mfp-iframe-holder .mfp-close::after {
            display: none;
        }
    }
    @media (hover: none) {
        .mfp-iframe-holder .mfp-close:hover { color: inherit; }
    }

    @media(min-width: 768px) {
        .box-tocart  > .fieldset {
            display: flex;
        }
        .quickview-block-top {
            display: flex;
            align-items: flex-end;
            padding: 20px 0;
        }

        .quickview-block-top .product.media,
        .quickview-block-top .quickview-block-top-price {
            width: 50%;
            max-width: 50%;
            box-sizing: border-box;
        }
    }
    @media(max-width: 767px) {
        .fixed-box.enable-fixed {
            position: fixed;
            z-index: 1000;
            background: #fff;
            left: 0;
            bottom: 0;
            right: 0;
        }

        .fixed-box.enable-fixed {
            display: flex;
            justify-content: space-between;
        }

        .fixed-box.enable-fixed > span {
            width: calc(50%);
            max-width: 50%;
            box-sizing: border-box;
            display: inline-block;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        #fixed-box-buy-now {
            background-color: #787878;
            color: #fff;
        }

        #fixed-box-buy-later {
            background-color: #343434;
            color: #fff;
        }

        /* .btn-buy-now-body .product-info-stock-sku,
        .btn-buy-later-body .product-info-stock-sku,
        .btn-buy-now-body .porto-block-html-top,
        .btn-buy-later-body .porto-block-html-top,
        .btn-buy-now-body .page-header ,
        .btn-buy-later-body .page-header,
        .btn-buy-now-body .product-social-links ,
        .btn-buy-later-body .product-social-links,
        .btn-buy-now-body .page-main.page-main-details,
        .btn-buy-later-body .page-main.page-main-details,
        .btn-buy-now-body .block-viewed-products-grid, 
        .btn-buy-later-body .block-viewed-products-grid,
        .btn-buy-now-body  #myBtn,
        .btn-buy-later-body  #myBtn  {
            display: none !important;
        } */

        .btn-buy-later-body #paypal-smart-button,
        .btn-buy-now-body #paypal-smart-button {
            display: none;
        }


        .mfp-iframe-holder .mfp-content {
            position: fixed;
            left: 0;
            bottom: 0;
            right: 0;
        }

        .btn-buy-later-body .column.main,
        .btn-buy-now-body .column.main {
            padding: 0 !important;
        }

        .btn-buy-now-body .product-info-main,
        .btn-buy-later-body .product-info-main {
            margin-bottom: 0 !important;
        }

        .btn-buy-now-body .product-options-bottom ,
        .btn-buy-later-body .product-options-bottom{
            margin: 0 !important;
        }

        .btn-buy-later-body .fotorama__nav-wrap,
        .btn-buy-now-body .fotorama__nav-wrap,
        .btn-buy-now-body .fotorama__fullscreen-icon,
        .btn-buy-later-body .fotorama__fullscreen-icon{
            display: none !important;
        }   

        .quickview-block-top {
            display: flex;
            align-items: flex-end;
            padding: 20px 0;
        }

        .quickview-block-top .product.media,
        .quickview-block-top .quickview-block-top-price {
            width: 50%;
            max-width: 50%;
            box-sizing: border-box;
        }

        .quickview-block-top .product.media .fotorama__stage {
            border-radius: 15px;
        }

        .quickview-block-top .quickview-block-top-price  .normal-price .price {
            color: red;
        }

        .btn-buy-later-body .box-tocart > .fieldset,
        .btn-buy-now-body .box-tocart > .fieldset  {
            display: flex;
            flex-direction: column;
        }

        .btn-buy-later-body .box-tocart > .fieldset .field.qty .label,
        .btn-buy-now-body .box-tocart > .fieldset  .field.qty .label {
            display: block;
        }

        .btn-buy-later-body .box-tocart > .fieldset .field.qty,
        .btn-buy-now-body .box-tocart > .fieldset  .field.qty  {
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .btn-buy-later-body  .product-add-form .box-tocart,
        .btn-buy-now-body  .product-add-form .box-tocart{
            border: none !important;
        }

        .quickview-block-top-price {
            padding-left: 15px;
        }

    }

    .box-tocart .field.qty .control {
        display: flex;
        align-items: center;
    }

    .box-tocart .field.qty .control > span {
        height: 100%;
        border: 1px solid #e7e7e7;
        display: block;
        min-height: 48px;
        line-height: 46px;
        width: 40px;
        text-align: center;
        cursor: pointer;
        box-sizing: border-box;
    }

    .box-tocart .field.qty .control #qty {
        min-height: 48px;
    }

    #paypal-smart-button {
        display: none !important;
    }

    .product-item-info .product-item-photo {
        z-index: 1 !important;
    }

</style>


