<?php
/** @var \Fovoso\Shipping\Block\ShippingPolicy $block */
?>
<?php $shippings = $block->getCollection(); ?>
<?php if ($shippings && sizeof($shippings)): ?>
    <div class="table-wrapper orders-history">
        <div class="search-bar">
            <form action="">
                <div class="fovoso-shipping-form">
                    <select name="country" id="country">
                        <option value="0">Choose a Country</option>
                        <?php foreach ($block->getCountry() as $value): ?>
                            <option value="<?= $value->getCountry(); ?>"><?= $value->getCountry(); ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="text" id="keyword" name="keyword" class="fovoso-keyword" placeholder="Search">
                    <button name="submit" id="fovoso_shipping_submit">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </div>
            </form>
        </div>
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('Country') ?></th>
                <th scope="col" class="col title"><?php echo __('Shipping Method') ?></th>
                <th scope="col" class="col product"><?php echo __('Shipping Time') ?></th>
                <th scope="col" class="col amount"><?php echo __('Costs') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($shippings as $shipping): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('country')) ?>" class="col id">
                        <?php echo $shipping->getCountry() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('shipping method')) ?>"
                        class="col title"><?= $shipping->getShippingMethod(); ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Shipping Time')) ?>" class="col product">
                        <?php echo $shipping->getShippingTime() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Costs')) ?>"
                        class="col amount"><?= $block->getFormattedPrice($shipping->getCosts()) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('No any record.'); ?></span></div>
<?php endif ?>
<script>
    require([
        'jquery'
    ], function($) {
        $('#country').on('change', function () {
            var country = $(this).val();
            if (country != 0 || country != null) {
                $.ajax({
                    method: "POST",
                    url: '<?= $block->escapeJs($block->getAjaxUrl()) ?>',
                    data: {
                        'country': country
                    },
                    success: function (result) {
                        if (result.html != null || result.html != "") {
                            $('#fovoso_policy').html(result.html);
                        } else {
                            console.log(result.html);
                        }
                    }
                });
            }
        });

        $('#fovoso_shipping_submit').on('click', function (e) {
            e.preventDefault();
            var country = $('#country').val();
            var keyword = $('#keyword').val();
            if (keyword != 0 || keyword != null) {
                $.ajax({
                    method: "POST",
                    url: '<?= $block->escapeJs($block->getAjaxUrl()) ?>',
                    data: {
                        'country': country,
                        'keyword': keyword
                    },
                    success: function (result) {
                        if (result.html != null || result.html != "") {
                            $('#fovoso_policy').html(result.html);
                        } else {
                            console.log(result.html);
                        }
                    }
                });
            }
        });
    });
</script>
