<?php
/** @var \Fovoso\Shipping\Block\ShippingList $block */
$res = $block->getListShipping();
$list = $res['items'];

$shop = $block->getShop();
$countries = $block->getListCountry();
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$shipFrom = $list[0]['shipping_from'] ?? ''; 
?>
<a style="width: 20px; height: 20px; padding: 0px; padding-right: 5px;" class="btn btn-light btn--s btn--inline btn-light--link _1bsnOp" href="/the1992.menswear?categoryId=100011&amp;itemId=13041440579"><svg enable-background="new 0 0 15 15" viewBox="0 0 15 15" x="0" y="0" stroke-width="0" class="shopee-svg-icon _3VTNCo"><path d="m13 1.9c-.2-.5-.8-1-1.4-1h-8.4c-.6.1-1.2.5-1.4 1l-1.4 4.3c0 .8.3 1.6.9 2.1v4.8c0 .6.5 1 1.1 1h10.2c.6 0 1.1-.5 1.1-1v-4.6c.6-.4.9-1.2.9-2.3zm-11.4 3.4 1-3c .1-.2.4-.4.6-.4h8.3c.3 0 .5.2.6.4l1 3zm .6 3.5h.4c.7 0 1.4-.3 1.8-.8.4.5.9.8 1.5.8.7 0 1.3-.5 1.5-.8.2.3.8.8 1.5.8.6 0 1.1-.3 1.5-.8.4.5 1.1.8 1.7.8h.4v3.9c0 .1 0 .2-.1.3s-.2.1-.3.1h-9.5c-.1 0-.2 0-.3-.1s-.1-.2-.1-.3zm8.8-1.7h-1v .1s0 .3-.2.6c-.2.1-.5.2-.9.2-.3 0-.6-.1-.8-.3-.2-.3-.2-.6-.2-.6v-.1h-1v .1s0 .3-.2.5c-.2.3-.5.4-.8.4-1 0-1-.8-1-.8h-1c0 .8-.7.8-1.3.8s-1.1-1-1.2-1.7h12.1c0 .2-.1.9-.5 1.4-.2.2-.5.3-.8.3-1.2 0-1.2-.8-1.2-.9z"></path></svg><a href="#"><?= $shop; ?></a></a>
<p style="margin-bottom: 0"> <?= $shipFrom ? __('From %1', $shipFrom) : '' ?></p>
<p style="padding-top: 5px;">Delivered to: <a id="myBtn2" href="#"><?= $res['location']; ?></a></p>
<div style="display: flex;">
    <div style="padding-top: 15px;width: 70%;">
        <?php foreach ($list as $value): ?>
            <div>
                <?php 
                $cost = $value['time_shipping'][0]['cost'] ?? 0; 
                $method = $value['time_shipping'][0]['method'] ?? __( 'Standard Shipping'); 
                $time = $value['time_shipping'][0]['time'] ?? ''; 
                $costFormatted = $priceHelper->currency((int)$cost);
                ?>
                <span style="font-weight: bold;">Shipping fee: <?= $costFormatted ?></span>
                <p style="padding: 5px; font-weight: 300;">
                    <?= $method ?>
                </p>

                <p>
                    <?= $time ? __('Time %1', $time) : '' ?>
                </p>
            </div>
            <?php break; ?>
        <?php endforeach; ?>
    </div>
    <div style="padding-top: 15px;"><a id="myBtn" href="#">More the selector</a></div>

    <!-- The Modal -->
    <div id="myModal" class="modal-shipping">

        <!-- Modal content -->
        <div class="modal-content-shipping">
            <span class="close">&times;</span>
            <div style="padding: 10px;font-size: small; font-weight: bold; text-align: center;" class="comet-modal-header">
                Shipping method
            </div>
            <div style="background: #f9f9f9;">
                <?php foreach ($list as $value): ?>   
                <?php $methods = $value['time_shipping'] ?? [];?>
                    <div>
                        <table>
                            <?php foreach($methods as $method): ?>
                            <?php 
                            $cost = $method['cost'] ?? 0;  
                            $costFormatted = $priceHelper->currency((int)$cost);
                            $time = $method['time'] ?? '';  
                            $title = $method['method'] ?? 0;
                            ?>
                            <tr>
                                <td>
                                    <span style="font-weight: bold;">Shipping fee: <?= $costFormatted ?></span>
                                    <p><?= $time ?></p>
                                    <p><?= $title ?></p>
                                </td>
                                <td>
                                    <div class="selectShipping nsce3"><span class="comet-icon comet-icon-selected " style="font-size: 12px; color: rgb(255, 255, 255);"><svg viewBox="0 0 1024 1024" width="1em" height="1em" fill="currentColor" aria-hidden="false" focusable="false" data-spm-anchor-id="a2g0o.detail.0.i13.5bb0270eq38mNr"><path d="M869.696 229.824a37.12 37.12 0 0 1 55.018667 49.706667l-2.410667 2.645333-464.213333 466.432a101.12 101.12 0 0 1-139.349334 3.818667l-3.989333-3.797334L101.696 534.613333a37.12 37.12 0 0 1 49.962667-54.805333l2.645333 2.410667 213.056 214.016c9.898667 9.856 25.386667 10.496 35.925333 1.962666l2.176-1.962666 464.213334-466.410667z"></path></svg></span></div>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>

                <?php endforeach; ?>
            </div>
        </div>

    </div>
    <div id="myModal2" class="modal-shipping2">

        <!-- Modal content -->
        <div class="modal-content-shipping2">
            <span class="close2">&times;</span>
            <div style="padding: 10px;font-size: small; font-weight: bold; text-align: center;" class="comet-modal-header">
                Ship to
            </div>
            <div>
                <select name="country" id="country">
                    <?php foreach ($countries as $key => $value): ?>
                        <option value="<?= $value; ?>" <?php echo $value == $res['location'] ? ' selected' : '' ?>><?= $value; ?></option>
                    <?php endforeach; ?>
                </select>
                <div style="margin: 0 auto; display: table; padding-top: 16px;" class="comet-modal-footer comet-modal-footer-horizontal">
                    <button style="line-height: 1px;" type="button" class="comet-btn comet-btn-primary">
                        <span style="font-size: inherit; color: white;" class="close">OK</span>
                    </button>
                </div>
            </div>
        </div>

    </div>

</div>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $( document ).ready(function() {

        });
        $(document).on("click", ".comet-btn-primary", function(e) {
            console.log( "click here!" );
            var url = window.location.origin + window.location.pathname;
            url = url.replace('#','');

            if (url.indexOf('?') > -1){
                url += '&country=' + $('#country').val()
            }else{
                url += '?country=' + $('#country').val()
            }
            window.location.href = url;
           // window.location.reload();
        });
        // Get the modal
        var modal = document.getElementById("myModal");
        var modal2 = document.getElementById("myModal2");

        // Get the button that opens the modal
        var btn = document.getElementById("myBtn");
        // Get the button that opens the modal
        var btn2 = document.getElementById("myBtn2");

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];
        // Get the <span> element that closes the modal
        var span2 = document.getElementsByClassName("close2")[0];

        // When the user clicks on the button, open the modal
        btn.onclick = function(e) {

            modal.style.display = "block";
            setTimeout(setPosition, 100);
            function setPosition() {
                $(document).scrollTop($('.modal-content-shipping').offset().top - $('.modal-content-shipping').outerHeight() );
            }

        }

        btn2.onclick = function() {

            modal2.style.display = "block";
            setTimeout(setPosition, 10);
            function setPosition() {
                $(document).scrollTop($('.modal-content-shipping2').offset().top - $('.modal-content-shipping2').outerHeight() );
            }

        }

        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
            modal.style.display = "none";
        }
        span2.onclick = function() {
            modal2.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
            if (event.target == modal2) {
                modal2.style.display = "none";
            }
        }
    });
</script>

<style>
    .comet-modal-footer-horizontal {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-direction: row-reverse;
        flex-direction: row-reverse;
    }
    .comet-modal-footer {
        -ms-flex-negative: 0;
        flex-shrink: 0;
    }
    .comet-btn-primary {
        padding-top: 4px;
        padding-bottom: 4px;
        background: linear-gradient(90deg,#ff640e,#ff3000) !important;
        color: #fff;
        border-width: 0;
    }
    .comet-btn {
        position: relative;
        display: inline-block;
        font-weight: 700;
        white-space: nowrap;
        text-align: center;
        background-image: none;
        border: 1px solid #999;
        cursor: pointer;
        transition: all .3s cubic-bezier(.645,.045,.355,1);
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        box-sizing: border-box;
        font-size: 16px;
        padding: 3px 12px;
        height: 32px;
        font-size: 14px;
        line-height: 24px;
        background: #fff;
        color: #222;
        border-radius: 16px;
    }
    /* The Modal (background) */
    #paypal-smart-button {
        padding: 2px 2px 2px 5px;
    }
    .modal-shipping, .modal-shipping2  {
        display: none; /* Hidden by default */
        position: absolute; /* Stay in place */
        z-index: 999999; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 400%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    /* Modal Content/Box */


    /* The Close Button */
    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    /* The Close Button */
    .close2 {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close2:hover,
    .close2:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    .selectShipping {
        background-image: linear-gradient(90deg,#ff7539,#ff0a0a);
    }
    ._37WgX {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-pack: center;
        justify-content: center;
        -ms-flex-align: center;
        align-items: center;
        width: 18px;
        height: 18px;
        background-image: linear-gradient(90deg,#ff7539,#ff0a0a);
        border-radius: 50%;
    }
    ._37WgX, .nsce3 {
        float: right;
    }
    .comet-icon {
        display: inline-block;
        font-style: normal;
        line-height: 0;
        text-align: center;
        text-transform: none;
        vertical-align: -0.125em;
        text-rendering: optimizeLegibility;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        font-size: 12px;
        color: rgb(255, 255, 255);
    }
    .nsce3 {
        width: 16px;
        height: 16px;
        border: 1px solid #ccc;
        border-radius: 50%;
        background-image: none;
    }
</style>
