<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact"
      action="<?php echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <h2><b><?php echo __('Contact Us') ?></b></h2><br />
    <div class="row">
        <div class="col-md-6">
            <div class="">
                <b>5A SYSTEMS LLC</b>
                <p><b><?php echo __('Address') ?>:</b><?php echo __('5555 West Loop South Suite 420 Bellaire,TX 77401 , USA') ?></p>
                <p>Sales@hacano.com</p>
                <p>Support@hacano.com</p>
                <p><?php echo __('If you have any questions, please fell free to get in touch with us. We will reply to you as soon as possible. Thank you!') ?></p>
            </div>
        </div>
        <div class="col-md-6">
            <p><?php echo __('Mobile') ?> : (+01)-713291 5755</p>
            <p><?php echo __('Free Call') ?> : (+1) 855-476-5050</p>
            <?= $block->getChildHtml('contactPage') ?>
<!--            <h3 style="font-size: 20px;"><b>Social</b></h3>-->
<!--            <div class="follow-icon">-->
<!--                <a href="#" target="_blank" class="icon icon_twitter nasa-tip nasa-tiped" rel="nofollow">-->
<!--                    <i class="fab fa-twitter"></i>-->
<!--                    <span class="icon-content">Follow us on Twitter</span>-->
<!--                </a>-->
<!--                <a href="#" target="_blank" class="icon icon_facebook nasa-tip" rel="nofollow">-->
<!--                    <i class='fab fa-facebook-f'></i>-->
<!--                    <span class="icon-content">Follow us on Facebook</span>-->
<!--                </a>-->
<!--                <a href="#" target="_blank" class="icon icon_pintrest nasa-tip" rel="nofollow">-->
<!--                    <i class="fab fa-pinterest"></i>-->
<!--                    <span class="icon-content">Follow us on Pinterest</span>-->
<!--                </a>-->
<!--                <a href="#" target="_blank" class="icon icon_instagram nasa-tip nasa-tiped" rel="nofollow">-->
<!--                    <i class="fab fa-instagram"></i>-->
<!--                    <span class="icon-content">Follow us on Instagram</span>-->
<!--                </a>-->
<!--            </div>-->
        </div>
    </div>
    <div class="row">
        <div class="fields col-md-6">
          <div class="field name required">
              <label class="label" for="name"><b><?php echo __('Your Name (required)') ?></b></label>
              <div class="control">
                  <input name="name" id="name" title="<?php echo __('Your Name (required)') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
              </div>
          </div>
        </div>
        <div class="fields col-md-6">
            <div class="field email required">
                <label class="label" for="email"><b><?php echo __('Your Email (required)') ?></b></label>
                <div class="control">
                    <input name="email" id="email" title="<?php echo __('Your Email (required)') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="fields col-md-12">
            <div class="field telephone">
                <label class="label" for="telephone"><b><?php echo __('Phone Number') ?></b></label>
                <div class="control">
                    <input name="telephone" id="telephone" title="<?php echo __('Phone Number') ?>" value="" class="input-text" type="text" />
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="fields col-md-12">
            <div class="field comment required">
                <label class="label" for="comment"><b><?php echo __('Your Message') ?></b></label>
                <div class="control">
                    <textarea name="comment" id="comment" title="<?php echo __('Your Message') ?>" class="input-text" cols="5" rows="8" data-validate="{required:true}"></textarea>
                </div>
            </div>
        </div>
    </div>
    <?= $block->getChildHtml('form.additional.info') ?>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('SUBSCRIBE') ?>" class="action submit" style="background: #f76b6a; border-color:#f76b6a; color: #fff">
                <span><?php echo __('SUBSCRIBE') ?></span>
            </button>
        </div>
    </div>
</form>
<style>
    .row {
        margin-bottom: 20px;
    }
    .icon.nasa-tip {
        background: transparent;
        color: #333;
        opacity: 0.8;
        margin-right: 20px;
        position: relative;
    }
    .icon-content {
        position: absolute;
        display: none;
        top: -10px;
        left: 50%;
        z-index: 9999;
        width: auto;
        height: auto;
        background: #333;
        border-color: #333;
        color: #fff;
        white-space: nowrap;
        text-transform: none;
        font-size: 12px;
        font-weight: normal;
        line-height: 1.4;
        padding: 5px 8px;
        -webkit-box-shadow: none;
        -moz-box-shadow: none;
        box-shadow: none;
        -webkit-border-radius: 2px;
        -moz-border-radius: 2px;
        border-radius: 2px;
        -webkit-transform: translate(-50%, -100%);
        -moz-transform: translate(-50%, -100%);
        -o-transform: translate(-50%, -100%);
        -ms-transform: translate(-50%, -100%);
        transform: translate(-50%, -100%);
    }
    .icon-content:after {
        top: 95%;
        left: 50%;
        content: " ";
        height: 0;
        width: 0;
        position: absolute;
        pointer-events: none;
        border: solid transparent;
        border-color: transparent;
        border-top-color: inherit;
        border-width: 6px;
        margin-left: -6px;
    }
    .tooltip-visible .icon-content {
        display: block !important;
    }
</style>
<script>
    require([
        'jquery'
    ], function ($) {
        "use strict";
        $('.icon.nasa-tip').hover(function () {
            $('.icon.nasa-tip').removeClass('tooltip-visible');
            $(this).addClass('tooltip-visible');
        }, function () {
            $('.icon.nasa-tip').removeClass('tooltip-visible');
        });
    });
</script>
