<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_GdprCookie
 */
?>
<?php
/** @var \Amasty\GdprCookie\Block\CookieBar $block */

if ($cookiePrivacyText = $block->getCookiePolicyText()) : ?>
    <?php 
        $settingBlock = $this->getLayout()->createBlock(\Amasty\GdprCookie\Block\Widget\Settings::class);
        $groups = $settingBlock->getAllGroups();
    ?>
    <div class="amgdprcookie-main-wrapper" style="display: none;">
        <form id="amgdprcookie-form">
            <div class="amgdprcookie-top">
                <span class="amgdprcookie-head">
                    <?= $block->escapeHtml(__('Cookie Settings')); ?>
                </span>
                <div class="amgdprcookie-btn-wrapper">
                    <button class="amgdprcookie-btn" id="amgdprcookie-btn-all">
                        <?= $block->escapeHtml(__('Allow all')); ?>
                    </button>
                    <button class="amgdprcookie-btn" id="amgdprcookie-btn-save">
                        <?= $block->escapeHtml(__('Save')); ?>
                    </button>
                </div>
            </div>
            <?php foreach ($groups as $groupId => $groupData): ?>
            <div class="amgdprcookie-container">
                <div class="amgdprcookie-header">
                    <h3 class="amgdprcookie-caption">
                        <?= $block->escapeHtml(__('%1 Cookies', $groupData['name'])); ?>
                    </h3>
                    <div class="amgdprcookie-toggle-cookie">
                        <input class="amgdprcookie-input <?= $groupData['isEssential'] ? 'disabled' : ''; ?>"
                            type="checkbox"
                            id="switchBox<?= /** @noEscape */ (int) $groupId; ?>"
                            name="groups[]"
                            value="<?= /** @noEscape */ (int) $groupId; ?>"
                            data-category-id="1"
                            data-is-system="1"
                            <?= $groupData['checked'] ? 'checked' : ''; ?>
                            <?= $groupData['isEssential'] ? 'onclick="return false;"' : ''; ?>
                        />
                        <label class="amgdprcookie-label" for="switchBox<?= /** @noEscape */ (int) $groupId; ?>"></label>
                    </div>
                </div>
                <p class="amgdprcookie-text">
                    <?= $block->escapeHtml($groupData['description']); ?>
                </p>
                <div class="amgdprcookie-options-wrapper"
                    data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                    <div class="amgdprcookie-check" data-role="collapsible">
                        <div class="amgdprcookie-options" data-role="trigger">
                            <?= $block->escapeHtml(__('List of cookies the %1 group collects', $groupData['name'])); ?>
                        </div>
                    </div>
                    <div class="amgdprcookie-content-wrapper" data-role="content">
                        <table class="amgdprcookie-table">
                            <thead>
                                <tr>
                                    <th class="amgdprcookie-title">
                                        <?= $block->escapeHtml(__('Cookie Name')); ?>
                                    </th>
                                    <th class="amgdprcookie-title">
                                        <?= $block->escapeHtml(__('Cookie Description')); ?>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($groupData['cookies'] as $cookie): ?>
                                <tr class="amgdprcookie-row">
                                    <td class="amgdprcookie-cell">
                                        <?= $block->escapeHtml($cookie['name']); ?>
                                    </td>
                                    <td class="amgdprcookie-cell desc">
                                        <?= $block->escapeHtml($cookie['description']); ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </form>
    </div>

    <script>
        require([
            'jquery', 
            'mage/url',
            'mage/cookies'
        ], function($, urlBuilder) {
            $(document).ready(function() {
                $('#amgdprcookie-btn-save').click(function (e) {
                    e.preventDefault();
                    var url = urlBuilder.build('gdprcookie/cookie/savegroups'),
                        form = $('#amgdprcookie-form')

                    $.ajax({
                        showLoader: true,
                        method: "POST",
                        url: url,
                        data: form.serialize()
                    }).done(function () {
                        $("#gdpr-cookie-block").remove();
                    });
                });

            })
        })
    </script>

    <div data-role="gdpr-cookie-container" data-bind="scope: 'gdpr-cookie-container'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
    {
        "[data-role=gdpr-cookie-container]": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "gdpr-cookie-container": {
                        "component": "Amasty_GdprCookie/js/cookies",
                        "noticeType": <?= $block->escapeHtml($block->getNoticeType()); ?>,
                        "policyText": <?= /** @escapeNotVerified */ $cookiePrivacyText; ?>,
                        "allowLink": "<?= $block->escapeUrl($block->getAllowLink()) ?>",
                        "settingsLink": "<?= $block->escapeUrl($block->getSettingsLink()) ?>",
                        "websiteInteraction": "<?= $block->escapeHtml($block->getWebsiteInteraction()); ?>",
                        "firstShowProcess": "<?= $block->escapeHtml($block->isProcessFirstShow()); ?>"
                    }
                }
            }
        }
    }
    </script>
    <style>
        .message.global.cookie.am-cookie {
        <?php if ($block->getBarLocation()) : ?>
            bottom: unset;
        <?php endif; ?>
            position: sticky;
            position: -webkit-sticky;
            z-index: 10;
            background-color: <?= $block->escapeHtml($block->getBackgroundBarCollor()); ?>;
        }

        div[data-role="gdpr-cookie-container"] {
                position: sticky;
                position: -webkit-sticky;
                z-index: 15;
            <?php if ((int)$block->getBarLocation()) : ?>
                top: 0;
            <?php else : ?>
                bottom: 0;
            <?php endif; ?>
        }

        .am-cookie .content p {
            color: <?= $block->escapeHtml($block->getTextBarCollor()); ?>;
        }

        .message.global.cookie a, .message.global.cookie a:hover {
            color: <?= $block->escapeHtml($block->getLinksBarCollor()); ?>;
        }
        .message.global.noscript, .message.global.cookie{
            background-color: <?= $block->escapeHtml($block->getBackgroundBarCollor()); ?>  !important;
        }
        .actions button.action.primary.cookiebar {
            background-color: <?= $block->escapeHtml($block->getButtonsBarCollor()); ?>;
            border-color: <?= $block->escapeHtml($block->getButtonsBarCollor()); ?>;
            color: <?= $block->escapeHtml($block->getButtonTextBarCollor()); ?>;
        }

        .actions button.action.primary.cookiebar:hover {
            opacity: 0.9;
        }

        #notice-cookie-block {
            display: none !important;
        }
    </style>

<?php endif; ?>
