<?php
/**
 * Copyright © 2018 Porto. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Smartwave\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper('Smartwave\Megamenu\Helper\Data');
    $_config = $_helper->getConfig('sw_megamenu');
    $columnsLimit = 0;
    $header_type = $_helper->getConfig('porto_settings/header/header_type');

    if($_config['general']['enable']) {
?>
<?php $_menu = $block->getMegamenuHtml(); ?>

<nav class="navigation sw-megamenu <?php if($header_type == 7 || $header_type == 8  || $header_type == 18): ?>side-megamenu<?php endif; ?>" role="navigation">
    <ul class="sw-megamenu-desktop">
        <?php echo $_menu; ?>
    </ul>
    <ul class="sw-megamenu-mobile" style="display: none">
        <?php echo $block->getMegaMenuMobileHtml(); ?>
    </ul>
    <div class="mobile-megamenu-parent">
        <?php echo $block->getMegaMenuMobileHtmlChild(); ?>
    </div>
    <div class="mobile-megamenu-child">
        <?php echo $block->getSubmenuLv1Html(); ?>
    </div>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'Smartwave_Megamenu/js/sw_megamenu'
    ], function ($) {
        $(".sw-megamenu").swMegamenu();
        $('ul.sw-megamenu-mobile li.ui-menu-item.level0.parent').on('click', function (e) {
            e.preventDefault();
            $('ul.sw-megamenu-mobile li.ui-menu-item.level0.parent').removeClass('mobile-parent-active');
            $('.mobile-megamenu-children').removeClass('mobile-active');
            $(this).addClass('mobile-parent-active');
            var cateId = $(this).attr('data-cateid');
            $('.submenu-cate-'+cateId).addClass('mobile-active');
        });
        $('.ui-menu-item.level0 .open-children-toggle').on('click', function () {
            var cateId = $(this).attr('data-cateid');
            $('.subchildmenu').removeClass('child-menu-active');
            $('.subchildmenu-cate-' + cateId).addClass('child-menu-active');
        });
        $('.megamenu-mobile-navigation-left').on('click', function () {
            $('.subchildmenu').removeClass('child-menu-active');
        });
    });
</script>
<?php
    } else {
?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit); ?>

<nav class="navigation sw-megamenu" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
</nav>

<?php
    }
?>
