<?php 
    $brands = $block->getListBrands(); 
    $customBlock = $block->getLayout()->createBlock('Magiccart\Shopbrand\Block\ListBrand');

    echo $this->getBase();
?>
<div class="list-brand-widget">
    <?php $i=0; foreach ($brands as $brand) :?>
        <div class="item">
            <a href="<?php /* @escapeNotVerified */ echo $block->getUrlBrand($brand) ?>">
                <img class="brand img-responsive" src="<?php /* @escapeNotVerified */ echo $block->getImage($brand)?>" alt="<?php /* @escapeNotVerified */ echo __($brand->getTitle()) ?>" title="<?php /* @escapeNotVerified */ echo __($brand->getTitle()) ?>" width="220" height="220" />
                <p class="number-product"><?php echo  $customBlock->getProductCount($brand).' Products'; ?></p>
            </a>
        </div>
    <?php endforeach ?>
   
</div>
<div class="loadmore-brands" data-content-type="text" data-appearance="default" data-element="main"><p><?= __('Show More'); ?></p></div>  
<style>
.list-brand-widget {
    display: grid;
    grid-template-columns: 20% 20% 20% 20% 20%;
    grid-gap: 20px;
    margin-left: auto !important;
    margin-right: auto !important;
    max-width: 1140px;
    padding: 0 20px;
}
.list-brand-widget .item{
    display: none;
}
.list-brand-widget .item a {
    display: block;
    width: 100%;
    height: 100%;
}
.list-brand-widget .item a img {
    width: 100%;
    height: 100%;
    object-fit: contain;
    transform: scale(0.7);
}
.loadmore-brands {
    width: 100%;
    margin-top: 80px;
    text-transform: capitalize;
}

.loadmore-brands p {
    border: 1px solid;
    max-width: 150px;
    width: 100%;
    clear: both;
    margin: 0 auto !important;
    padding: 10px;
    font-weight: 700;
    color: black;
    font-size: 1em;
    text-align: center;
    cursor: pointer;
}
@media only screen and (max-width: 767px){
    .list-brand-widget {
        grid-template-columns: auto auto auto auto;
        grid-gap: 15px;
    }
    .list-brand-widget .item a img{
        transform: scale(0.9);
    }
}
</style>

<script type="text/javascript">
    require([
        'jquery',
        ], function($){
            $(document).ready(function(){

                var UrlBrandList  = window.location.origin+'/shopbrand';
                //  brands
                if($(window).width() < 767) {
                    $(".list-brand-widget .item:lt(8)").show();

                    $(".loadmore-brands").on('click', function(event) {
                        event.preventDefault();
                        var $hidden =$(".list-brand-widget .item:hidden");
                        $($hidden).slice(0, 8).fadeIn(800);

                        if ($hidden.length == 0) {
                            $(this).fadeOut();
                            window.location.href = UrlBrandList;
                        }
                    });
                }else {
                    $(".list-brand-widget .item:lt(10)").show();

                    $(".loadmore-brands").on('click', function(event) {
                            event.preventDefault();
                            var $hidden =$(".list-brand-widget .item:hidden");
                            $($hidden).slice(0, 10).fadeIn(800);

                            if ($hidden.length == 0) {
                                $(this).fadeOut();
                                window.location.href = UrlBrandList;
                            }
                    });
                }


            })
    });
</script>